k9s_windows_url: "https://github.com/derailed/k9s/releases/latest/download/k9s_Windows_amd64.tar.gz"
k9s_windows_dest: "C:\\Program Files\\k9s\\k9s.tar.gz"
k9s_windows_extract: "C:\\Program Files\\k9s"
